export const LIGHT_THEME = {
    BACKGROUND: '#FAF9F9',
    TEXT: '#555B6E',
    PRIMARY: '#BEE3DB',
    SECONDARY: '#89B0AE',
    TERTIARY: '#FFD6BA',
    BORDER: '#ECE9E9',
    COLORED_BUTTON_TEXT: '#FFFFFF'
}